/**
 * ssr.ts — Server-Side Rendering Pipeline (Dev Mode)
 *
 * Handles the full page render cycle for `nuke dev`:
 *
 *   1. Match the incoming URL to a page file in app/pages using the file-system
 *      router.
 *   2. Discover the layout chain (layout.tsx files from root to the page dir).
 *   3. Dynamically import the page and layout modules (always fresh via tsImport).
 *   4. Walk the import tree to discover all "use client" components.
 *   5. Render the wrapped element tree with the async renderer.
 *   6. Flush the html-store (title, meta, link, script, style tags).
 *   7. Assemble and send the full HTML document including:
 *        - The rendered app HTML
 *        - An importmap pointing react/nukejs to the bundled versions
 *        - A __n_data JSON blob with hydration IDs and runtime config
 *        - An inline bootstrap <script> that calls initRuntime()
 *        - (dev only) A /__hmr.js script for Hot Module Replacement
 *
 * In production, a pre-built standalone handler (generated by build-common.ts)
 * handles each page without dynamic imports or file-system access.
 *
 * HMR fast path:
 *   When the request URL contains `__hmr=1` (added by the HMR client during
 *   soft navigation), the renderer skips client-component renderToString
 *   (ctx.skipClientSSR = true).  This speeds up HMR reloads because the
 *   client already has the DOM in place and only needs fresh server markup.
 *
 * Head tag sentinels:
 *   Every useHtml()-generated <meta>, <link>, <style>, and <script> tag is
 *   wrapped in <!--n-head-->…<!--/n-head--> comment sentinels.  The client
 *   runtime uses these to diff and sync head tags on SPA navigation without
 *   touching permanent tags (charset, viewport, importmap, runtime script).
 *   Pages with no useHtml head tags emit no sentinels.
 */

import path from 'path';
import fs   from 'fs';
import { createElement } from 'react';
import { pathToFileURL } from 'url';
import { tsImport } from 'tsx/esm/api';
import type { ServerResponse } from 'http';
import { log, getDebugLevel, type DebugLevel } from './logger';
import { matchRoute, findLayoutsForRoute } from './router';
import { findClientComponentsInTree } from './component-analyzer';
import { renderElementToHtml, type RenderContext } from './renderer';
import { runWithRequestStore, normaliseHeaders, sanitiseHeaders } from './request-store';
import type { IncomingMessage } from 'http';
import {
  runWithHtmlStore,
  resolveTitle,
  type HtmlStore,
  type HtmlAttrs,
  type BodyAttrs,
  type MetaTag,
  type LinkTag,
  type ScriptTag,
  type StyleTag,
} from './html-store';

// ─── Layout wrapping ──────────────────────────────────────────────────────────

/**
 * Wraps a page element in its layout chain, outermost-first.
 * Each layout receives `{ children: innerElement }` as props.
 *
 * tsImport creates a fresh isolated module namespace per call so edits to
 * layouts are reflected immediately without a server restart.
 */
async function wrapWithLayouts(pageElement: any, layoutPaths: string[]): Promise<any> {
  let element = pageElement;
  // Iterate in reverse so the outermost layout wraps last (becomes the root).
  for (let i = layoutPaths.length - 1; i >= 0; i--) {
    const { default: LayoutComponent } = await tsImport(
      pathToFileURL(layoutPaths[i]).href,
      { parentURL: import.meta.url },
    );
    element = createElement(LayoutComponent, { children: element });
  }
  return element;
}

// ─── Debug level conversion ───────────────────────────────────────────────────

/**
 * Converts the server-side DebugLevel to the string format expected by the
 * browser's makeLogger() function in bundle.ts.
 */
function toClientDebugLevel(level: DebugLevel): string {
  if (level === true)    return 'verbose';
  if (level === 'info')  return 'info';
  if (level === 'error') return 'error';
  return 'silent';
}

// ─── HTML serialization helpers ───────────────────────────────────────────────

function escapeAttr(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}

/** Serializes an attribute map to `key="value" …`, omitting undefined/false values. */
function renderAttrs(attrs: Record<string, string | boolean | undefined>): string {
  return Object.entries(attrs)
    .filter(([, v]) => v !== undefined && v !== false)
    .map(([k, v]) => v === true ? k : `${k}="${escapeAttr(String(v))}"`)
    .join(' ');
}

/** Returns `<tag attrs>` or `<tag>` depending on whether attrs are non-empty. */
function openTag(tag: string, attrs: Record<string, string | undefined>): string {
  const str = renderAttrs(attrs);
  return str ? `<${tag} ${str}>` : `<${tag}>`;
}

// ─── Head tag renderers ───────────────────────────────────────────────────────

function metaKey(k: string): string {
  return k === 'httpEquiv' ? 'http-equiv' : k;
}

function linkKey(k: string): string {
  if (k === 'hrefLang')    return 'hreflang';
  if (k === 'crossOrigin') return 'crossorigin';
  return k;
}

function renderMetaTag(tag: MetaTag): string {
  const attrs: Record<string, string | undefined> = {};
  for (const [k, v] of Object.entries(tag)) if (v !== undefined) attrs[metaKey(k)] = v;
  return `  <meta ${renderAttrs(attrs)} />`;
}

function renderLinkTag(tag: LinkTag): string {
  const attrs: Record<string, string | undefined> = {};
  for (const [k, v] of Object.entries(tag)) if (v !== undefined) attrs[linkKey(k)] = v;
  return `  <link ${renderAttrs(attrs)} />`;
}

function renderScriptTag(tag: ScriptTag): string {
  const attrs: Record<string, string | boolean | undefined> = {
    src:         tag.src,
    type:        tag.type,
    crossorigin: tag.crossOrigin,
    integrity:   tag.integrity,
    defer:       tag.defer,
    async:       tag.async,
    nomodule:    tag.noModule,
  };
  const attrStr = renderAttrs(attrs);
  const open    = attrStr ? `<script ${attrStr}>` : '<script>';
  return `  ${open}${tag.src ? '' : (tag.content ?? '')}</script>`;
}

function renderStyleTag(tag: StyleTag): string {
  const media = tag.media ? ` media="${escapeAttr(tag.media)}"` : '';
  return `  <style${media}>${tag.content ?? ''}</style>`;
}

/**
 * Renders all useHtml()-sourced head tags wrapped in <!--n-head--> sentinels.
 * Scripts with position='body' are excluded here — they go in renderManagedBodyScripts().
 * Returns an empty array when none of the stores have any tags (no sentinels
 * emitted for pages that don't call useHtml).
 */
function renderManagedHeadTags(store: HtmlStore): string[] {
  const headScripts = store.script.filter(s => (s.position ?? 'head') === 'head');
  const tags = [
    ...store.meta.map(renderMetaTag),
    ...store.link.map(renderLinkTag),
    ...store.style.map(renderStyleTag),
    ...headScripts.map(renderScriptTag),
  ];
  if (tags.length === 0) return [];
  return ['  <!--n-head-->', ...tags, '  <!--/n-head-->'];
}

/**
 * Renders all useHtml()-sourced scripts with position='body', wrapped in
 * <!--n-body-scripts-->…<!--/n-body-scripts--> sentinels.
 * Injected just before </body> so scripts execute after page content is in the DOM.
 * Returns an empty array when there are no body-position scripts.
 */
function renderManagedBodyScripts(store: HtmlStore): string[] {
  const bodyScripts = store.script.filter(s => s.position === 'body');
  if (bodyScripts.length === 0) return [];
  return ['  <!--n-body-scripts-->', ...bodyScripts.map(renderScriptTag), '  <!--/n-body-scripts-->'];
}

// ─── Core render helper ───────────────────────────────────────────────────────

/**
 * Renders a specific page file and writes the full HTML response.
 * Shared by the normal render path and the _404/_500 error page fallbacks.
 */
async function renderFile(
  filePath:      string,
  params:        Record<string, string | string[]>,
  url:           string,
  pagesDir:      string,
  isDev:         boolean,
  res:           ServerResponse,
  req:           IncomingMessage | undefined,
  statusCode:    number,
  skipClientSSR: boolean,
): Promise<void> {
  const cleanUrl = url.split('?')[0];

  // ── Query string parsing ─────────────────────────────────────────────────────
  const searchParams = new URL(url, 'http://localhost').searchParams;
  const queryParams: Record<string, string | string[]> = {};
  searchParams.forEach((_, k) => {
    if (!(k in params)) {
      const all = searchParams.getAll(k);
      queryParams[k] = all.length > 1 ? all : all[0];
    }
  });
  const mergedParams = { ...queryParams, ...params };

  // ── Headers ──────────────────────────────────────────────────────────────────
  const rawHeaders  = req?.headers ?? {};
  const normHeaders = normaliseHeaders(rawHeaders as Record<string, string | string[] | undefined>);
  const safeHeaders = sanitiseHeaders(rawHeaders as Record<string, string | string[] | undefined>);

  // ── Module import ─────────────────────────────────────────────────────────────
  const layoutPaths = findLayoutsForRoute(filePath, pagesDir);
  const { default: PageComponent } = await tsImport(
    pathToFileURL(filePath).href,
    { parentURL: import.meta.url },
  );
  const wrappedElement = await wrapWithLayouts(
    createElement(PageComponent, mergedParams),
    layoutPaths,
  );

  // ── Client component discovery ───────────────────────────────────────────────
  const registry = new Map<string, string>();
  for (const [id, p] of findClientComponentsInTree(filePath, pagesDir))
    registry.set(id, p);
  for (const layoutPath of layoutPaths)
    for (const [id, p] of findClientComponentsInTree(layoutPath, pagesDir))
      registry.set(id, p);

  // ── Rendering ─────────────────────────────────────────────────────────────────
  const ctx: RenderContext = { registry, hydrated: new Set(), skipClientSSR };

  let appHtml = '';
  const store: HtmlStore = await runWithRequestStore(
    {
      url,
      pathname: cleanUrl,
      params,
      query:    queryParams,
      headers:  normHeaders,
    },
    () => runWithHtmlStore(async () => {
      appHtml = await renderElementToHtml(wrappedElement, ctx);
    }),
  );

  // ── Head assembly ─────────────────────────────────────────────────────────────
  const pageTitle = resolveTitle(store.titleOps, 'NukeJS');

  const headLines: string[] = [
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    `  <title>${escapeAttr(pageTitle)}</title>`,
    ...renderManagedHeadTags(store),
  ];

  // ── Runtime data blob ─────────────────────────────────────────────────────────
  const runtimeData = JSON.stringify({
    hydrateIds: [...ctx.hydrated],
    allIds:     [...registry.keys()],
    url,
    params,
    query:   queryParams,
    headers: safeHeaders,
    debug: toClientDebugLevel(getDebugLevel()),
  })
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026');

  // ── Body scripts ──────────────────────────────────────────────────────────────
  const bodyScriptLines = renderManagedBodyScripts(store);
  const bodyScriptsHtml = bodyScriptLines.length > 0
    ? '\n' + bodyScriptLines.join('\n') + '\n'
    : '';

  // ── Full document ─────────────────────────────────────────────────────────────
  const html = `<!DOCTYPE html>
${openTag('html', store.htmlAttrs)}
<head>
${headLines.join('\n')}
</head>
${openTag('body', store.bodyAttrs)}
  <div id="app">${appHtml}</div>

  <script id="__n_data" type="application/json">${runtimeData}</script>

  <script type="importmap">
{
  "imports": {
    "react":             "/__react.js",
    "react-dom/client":  "/__react.js",
    "react/jsx-runtime": "/__react.js",
    "nukejs":            "/__n.js"
  }
}
  </script>

  <script type="module">
    await import('react');
    const { initRuntime } = await import('nukejs');
    const data = JSON.parse(document.getElementById('__n_data').textContent);
    initRuntime(data);
  </script>

  ${isDev ? '<script type="module" src="/__hmr.js"></script>' : ''}
${bodyScriptsHtml}</body>
</html>`;

  res.statusCode = statusCode;
  res.setHeader('Content-Type', 'text/html');
  res.end(html);
}

// ─── Error page helper ────────────────────────────────────────────────────────

/**
 * Converts any thrown value into a plain props object safe to pass as React
 * props and serialise into the page.
 *
 *   error.message  — human-readable description (string)
 *   error.status   — HTTP status code, if present (number | undefined)
 *   error.stack    — stack trace in dev only, omitted in production
 */
function serializeError(err: unknown): Record<string, string | string[]> {
  if (err instanceof Error) {
    const props: Record<string, string> = {
      errorMessage: err.message,
    };
    if (process.env.NODE_ENV !== 'production' && err.stack)
      props.errorStack = err.stack;
    const status = (err as any).status ?? (err as any).statusCode;
    if (status != null)
      props.errorStatus = String(status);
    return props;
  }
  return { errorMessage: String(err) };
}

/**
 * Attempts to render `_404.tsx` or `_500.tsx` from pagesDir.
 * Returns true if the error page was found and rendered, false otherwise.
 */
async function tryRenderErrorPage(
  statusCode: number,
  pagesDir:   string,
  res:        ServerResponse,
  isDev:      boolean,
  req?:       IncomingMessage,
  error?:     unknown,
): Promise<boolean> {
  const errorFile = path.join(pagesDir, `_${statusCode}.tsx`);
  if (!fs.existsSync(errorFile)) return false;

  // Serialize the error into safe props the page component can read.
  const errorProps = error != null ? serializeError(error) : {};

  try {
    await renderFile(errorFile, errorProps, '/', pagesDir, isDev, res, req, statusCode, false);
    return true;
  } catch (err) {
    log.error(`Error rendering _${statusCode}.tsx:`, err);
    return false;
  }
}

// ─── Main SSR handler ─────────────────────────────────────────────────────────

/**
 * Renders a page for the given URL and writes the full HTML response.
 *
 * @param url       The raw request URL (may include query string).
 * @param res       Node ServerResponse to write to.
 * @param pagesDir  Absolute path to the app/pages directory.
 * @param isDev     When true, injects the HMR client script into the page.
 */
export async function serverSideRender(
  url:      string,
  res:      ServerResponse,
  pagesDir: string,
  isDev   = false,
  req?:     IncomingMessage,
): Promise<void> {
  const skipClientSSR = url.includes('__hmr=1');
  const cleanUrl      = url.split('?')[0];

  // ── Route resolution ────────────────────────────────────────────────────────
  const routeMatch = matchRoute(cleanUrl, pagesDir);
  if (!routeMatch) {
    log.verbose(`No route found for: ${url}`);
    if (await tryRenderErrorPage(404, pagesDir, res, isDev, req)) return;
    res.statusCode = 404;
    res.end('Page not found');
    return;
  }

  const { filePath, params, routePattern } = routeMatch;
  log.verbose(`SSR ${cleanUrl} -> ${path.relative(process.cwd(), filePath)}`);

  try {
    await renderFile(filePath, params, url, pagesDir, isDev, res, req, 200, skipClientSSR);
  } catch (err) {
    log.error('SSR render error:', err);
    if (await tryRenderErrorPage(500, pagesDir, res, isDev, req, err)) return;
    res.statusCode = 500;
    res.end('Internal Server Error');
  }
}