/**
 * ssr.ts — Server-Side Rendering Pipeline (Dev Mode)
 *
 * Handles the full page render cycle for `nuke dev`:
 *
 *   1. Match the incoming URL to a page file in app/pages using the file-system
 *      router.
 *   2. Discover the layout chain (layout.tsx files from root to the page dir).
 *   3. Dynamically import the page and layout modules (always fresh via tsImport).
 *   4. Walk the import tree to discover all "use client" components.
 *   5. Render the wrapped element tree with the async renderer.
 *   6. Flush the html-store (title, meta, link, script, style tags).
 *   7. Assemble and send the full HTML document including:
 *        - The rendered app HTML
 *        - An importmap pointing react/nukejs to the bundled versions
 *        - A __n_data JSON blob with hydration IDs and runtime config
 *        - An inline bootstrap <script> that calls initRuntime()
 *        - (dev only) A /__hmr.js script for Hot Module Replacement
 *
 * In production, a pre-built standalone handler (generated by build-common.ts)
 * handles each page without dynamic imports or file-system access.
 *
 * HMR fast path:
 *   When the request URL contains `__hmr=1` (added by the HMR client during
 *   soft navigation), the renderer skips client-component renderToString
 *   (ctx.skipClientSSR = true).  This speeds up HMR reloads because the
 *   client already has the DOM in place and only needs fresh server markup.
 *
 * Head tag sentinels:
 *   Every useHtml()-generated <meta>, <link>, <style>, and <script> tag is
 *   wrapped in <!--n-head-->…<!--/n-head--> comment sentinels.  The client
 *   runtime uses these to diff and sync head tags on SPA navigation without
 *   touching permanent tags (charset, viewport, importmap, runtime script).
 *   Pages with no useHtml head tags emit no sentinels.
 */

import path from 'path';
import { createElement } from 'react';
import { pathToFileURL } from 'url';
import { tsImport } from 'tsx/esm/api';
import type { ServerResponse } from 'http';
import { log, getDebugLevel, type DebugLevel } from './logger';
import { matchRoute, findLayoutsForRoute } from './router';
import { findClientComponentsInTree } from './component-analyzer';
import { renderElementToHtml, type RenderContext } from './renderer';
import {
  runWithHtmlStore,
  resolveTitle,
  type HtmlStore,
  type HtmlAttrs,
  type BodyAttrs,
  type MetaTag,
  type LinkTag,
  type ScriptTag,
  type StyleTag,
} from './html-store';

// ─── Layout wrapping ──────────────────────────────────────────────────────────

/**
 * Wraps a page element in its layout chain, outermost-first.
 * Each layout receives `{ children: innerElement }` as props.
 *
 * tsImport creates a fresh isolated module namespace per call so edits to
 * layouts are reflected immediately without a server restart.
 */
async function wrapWithLayouts(pageElement: any, layoutPaths: string[]): Promise<any> {
  let element = pageElement;
  // Iterate in reverse so the outermost layout wraps last (becomes the root).
  for (let i = layoutPaths.length - 1; i >= 0; i--) {
    const { default: LayoutComponent } = await tsImport(
      pathToFileURL(layoutPaths[i]).href,
      { parentURL: import.meta.url },
    );
    element = createElement(LayoutComponent, { children: element });
  }
  return element;
}

// ─── Debug level conversion ───────────────────────────────────────────────────

/**
 * Converts the server-side DebugLevel to the string format expected by the
 * browser's makeLogger() function in bundle.ts.
 */
function toClientDebugLevel(level: DebugLevel): string {
  if (level === true)    return 'verbose';
  if (level === 'info')  return 'info';
  if (level === 'error') return 'error';
  return 'silent';
}

// ─── HTML serialization helpers ───────────────────────────────────────────────

function escapeAttr(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}

/** Serializes an attribute map to `key="value" …`, omitting undefined/false values. */
function renderAttrs(attrs: Record<string, string | boolean | undefined>): string {
  return Object.entries(attrs)
    .filter(([, v]) => v !== undefined && v !== false)
    .map(([k, v]) => v === true ? k : `${k}="${escapeAttr(String(v))}"`)
    .join(' ');
}

/** Returns `<tag attrs>` or `<tag>` depending on whether attrs are non-empty. */
function openTag(tag: string, attrs: Record<string, string | undefined>): string {
  const str = renderAttrs(attrs);
  return str ? `<${tag} ${str}>` : `<${tag}>`;
}

// ─── Head tag renderers ───────────────────────────────────────────────────────

function metaKey(k: string): string {
  return k === 'httpEquiv' ? 'http-equiv' : k;
}

function linkKey(k: string): string {
  if (k === 'hrefLang')    return 'hreflang';
  if (k === 'crossOrigin') return 'crossorigin';
  return k;
}

function renderMetaTag(tag: MetaTag): string {
  const attrs: Record<string, string | undefined> = {};
  for (const [k, v] of Object.entries(tag)) if (v !== undefined) attrs[metaKey(k)] = v;
  return `  <meta ${renderAttrs(attrs)} />`;
}

function renderLinkTag(tag: LinkTag): string {
  const attrs: Record<string, string | undefined> = {};
  for (const [k, v] of Object.entries(tag)) if (v !== undefined) attrs[linkKey(k)] = v;
  return `  <link ${renderAttrs(attrs)} />`;
}

function renderScriptTag(tag: ScriptTag): string {
  const attrs: Record<string, string | boolean | undefined> = {
    src:         tag.src,
    type:        tag.type,
    crossorigin: tag.crossOrigin,
    integrity:   tag.integrity,
    defer:       tag.defer,
    async:       tag.async,
    nomodule:    tag.noModule,
  };
  const attrStr = renderAttrs(attrs);
  const open    = attrStr ? `<script ${attrStr}>` : '<script>';
  return `  ${open}${tag.src ? '' : (tag.content ?? '')}</script>`;
}

function renderStyleTag(tag: StyleTag): string {
  const media = tag.media ? ` media="${escapeAttr(tag.media)}"` : '';
  return `  <style${media}>${tag.content ?? ''}</style>`;
}

/**
 * Renders all useHtml()-sourced head tags wrapped in <!--n-head--> sentinels.
 * Returns an empty array when none of the stores have any tags (no sentinels
 * emitted for pages that don't call useHtml).
 */
function renderManagedHeadTags(store: HtmlStore): string[] {
  const tags = [
    ...store.meta.map(renderMetaTag),
    ...store.link.map(renderLinkTag),
    ...store.style.map(renderStyleTag),
    ...store.script.map(renderScriptTag),
  ];
  if (tags.length === 0) return [];
  return ['  <!--n-head-->', ...tags, '  <!--/n-head-->'];
}

// ─── Main SSR handler ─────────────────────────────────────────────────────────

/**
 * Renders a page for the given URL and writes the full HTML response.
 *
 * @param url       The raw request URL (may include query string).
 * @param res       Node ServerResponse to write to.
 * @param pagesDir  Absolute path to the app/pages directory.
 * @param isDev     When true, injects the HMR client script into the page.
 */
export async function serverSideRender(
  url:      string,
  res:      ServerResponse,
  pagesDir: string,
  isDev = false,
): Promise<void> {
  const skipClientSSR = url.includes('__hmr=1');
  const cleanUrl      = url.split('?')[0];

  // ── Route resolution ────────────────────────────────────────────────────────
  const routeMatch = matchRoute(cleanUrl, pagesDir);
  if (!routeMatch) {
    log.verbose(`No route found for: ${url}`);
    res.statusCode = 404;
    res.end('Page not found');
    return;
  }

  const { filePath, params, routePattern } = routeMatch;
  log.verbose(`SSR ${cleanUrl} -> ${path.relative(process.cwd(), filePath)}`);

  // ── Module import ───────────────────────────────────────────────────────────
  // tsImport bypasses Node's ESM module cache entirely so edits are reflected
  // immediately on every request in dev.
  const layoutPaths = findLayoutsForRoute(filePath, pagesDir);
  const { default: PageComponent } = await tsImport(
    pathToFileURL(filePath).href,
    { parentURL: import.meta.url },
  );
  const wrappedElement = await wrapWithLayouts(
    createElement(PageComponent, params),
    layoutPaths,
  );

  // ── Client component discovery ──────────────────────────────────────────────
  // Walk the import tree for both the page and its layout chain.
  const registry = new Map<string, string>();
  for (const [id, p] of findClientComponentsInTree(filePath, pagesDir))
    registry.set(id, p);
  for (const layoutPath of layoutPaths)
    for (const [id, p] of findClientComponentsInTree(layoutPath, pagesDir))
      registry.set(id, p);

  log.verbose(
    `Page ${routePattern}: found ${registry.size} client component(s)`,
    `[${[...registry.keys()].join(', ')}]`,
  );

  // ── Rendering ───────────────────────────────────────────────────────────────
  const ctx: RenderContext = { registry, hydrated: new Set(), skipClientSSR };

  let appHtml = '';
  const store: HtmlStore = await runWithHtmlStore(async () => {
    appHtml = await renderElementToHtml(wrappedElement, ctx);
  });

  // ── Head assembly ───────────────────────────────────────────────────────────
  const pageTitle = resolveTitle(store.titleOps, 'SSR App');

  const headLines: string[] = [
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    `  <title>${escapeAttr(pageTitle)}</title>`,
    ...renderManagedHeadTags(store),
  ];

  // ── Runtime data blob ───────────────────────────────────────────────────────
  // Escape </script> sequences so the JSON cannot break out of the script tag.
  const runtimeData = JSON.stringify({
    hydrateIds: [...ctx.hydrated],
    allIds:     [...registry.keys()],
    url,
    params,
    debug: toClientDebugLevel(getDebugLevel()),
  })
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026');

  // ── Full document ───────────────────────────────────────────────────────────
  const html = `<!DOCTYPE html>
${openTag('html', store.htmlAttrs)}
<head>
${headLines.join('\n')}
</head>
${openTag('body', store.bodyAttrs)}
  <div id="app">${appHtml}</div>

  <script id="__n_data" type="application/json">${runtimeData}</script>

  <script type="importmap">
{
  "imports": {
    "react":             "/__react.js",
    "react-dom/client":  "/__react.js",
    "react/jsx-runtime": "/__react.js",
    "nukejs":            "/__n.js"
  }
}
  </script>

  <script type="module">
    await import('react');
    const { initRuntime } = await import('nukejs');
    const data = JSON.parse(document.getElementById('__n_data').textContent);
    initRuntime(data);
  </script>

  ${isDev ? '<script type="module" src="/__hmr.js"></script>' : ''}
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html');
  res.end(html);
}